<a href="https://colab.research.google.com/github/akritidu/Multi-label-Classification-in-the-Home-Improvement/blob/main/LSTM_Bi_LSTM_GRU_Bi_GRU.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Load and clean parameter**

In [3]:
from numpy import array
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Activation, Dropout, Dense
from tensorflow.keras.layers import Flatten, LSTM, GRU, Bidirectional, GlobalAveragePooling1D
from tensorflow.keras.layers import GlobalMaxPooling1D, SpatialDropout1D, GlobalMaxPool1D, BatchNormalization
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Embedding
# from sklearn.model_selection import train_test_split
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.layers import Input
from tensorflow.keras.layers import Concatenate

import pandas as pd
import numpy as np
import re


In [28]:
df = pd.read_csv('Phishload3columnasV3sinNaN.csv') #actual


In [29]:
df

contexts  ham  phishing
0      <!DOCTYPE html>\r\n<html xmlns="http://www.w3....    1         0
1      <!DOCTYPE html>\r\n<html xmlns="http://www.w3....    1         0
2      <!DOCTYPE html>\r\n<html xmlns="http://www.w3....    1         0
3      <!DOCTYPE html>\r\n<html xmlns="http://www.w3....    1         0
4      <!DOCTYPE html>\r\n<html xmlns="http://www.w3....    1         0
5      <!DOCTYPE html>\r\n<!-- Sysops: Please do not ...    1         0
6      <!-- ServerInfo: BAYIDSLGN1M58 2012.01.05.13.5...    1         0
7      <!DOCTYPE html>\r\n<html xmlns="http://www.w3....    1         0
8      <!DOCTYPE html>\r\n<html xmlns="http://www.w3....    1         0
9      <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 T...    1         0
10     <!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 T...    1         0
11     <!DOCTYPE html>\r\n<html xmlns="http://www.w3....    1         0
12     <!DOCTYPE html>\r\n<html xmlns="http://www.w3....    1         0
13     <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 S...    1         0
14     <!DOCTYPE html>\r\n<html xmlns="http://www.w3....    1         0
15     <!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 T...    1         0
16     <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 T...    1         0
17     <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 T...    1         0
18     <!DOCTYPE html>\r\n<html xmlns="http://www.w3....    1         0
19     <!DOCTYPE html>\r\n<html xmlns="http://www.w3....    1         0
20     <!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 T...    1         0
21     <!DOCTYPE html>\r\n<html xmlns="http://www.w3....    1         0
22     <!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 T...    1         0
23     <!DOCTYPE html>\r\n<html xmlns="http://www.w3....    1         0
24     <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 T...    1         0
25     <!DOCTYPE html>\r\n<html xmlns="http://www.w3....    1         0
26     <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 T...    1         0
27     <!DOCTYPE html>\r\n<html xmlns="http://www.w3....    1         0
28     <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//...    1         0
29     <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 T...    1         0
...                                                  ...  ...       ...
10344  <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 T...    1         0
10345  <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 T...    1         0
10346  <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 T...    1         0
10347  <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 T...    1         0
10348  <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 S...    1         0
10349  \r\n\r\n<!DOCTYPE html PUBLIC "-//W3C//DTD XHT...    1         0
10350  \r\n<HTML>\r\n<HEAD>\r\n<link rel="shortcut ic...    1         0
10351  <!DOCTYPE html>\n\t<html xml:lang="en" lang="e...    1         0
10352  \n<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0...    1         0
10353  <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 S...    1         0
10354  <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 T...    1         0
10355                 <h1>Bad Request (Invalid URL)</h1>    1         0
10356  \n\n\n\n\n<html>\n\t<head>\n\t\t<title>Optimum...    1         0
10357  <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 T...    1         0
10358  <!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 T...    1         0
10359  \n\n\n\n<!DOCTYPE html PUBLIC \"-//W3C//DTD XH...    1         0
10360  <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 T...    1         0
10361  <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 T...    1         0
10362  \r\n\r\n\r\n\r\n\r\n\r\n\n\n<!DOCTYPE HTML PUB...    1         0
10363  \r\n\r\n<!--[if IE]><![endif]-->\r\n<!doctype ...    1         0
10364  \r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r...    1         0
10365  \r\n      \r\n<!DOCTYPE HTML PUBLIC "-//W3C//D...    1         0
10366  \r\n<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1...    1         0
10367          <!DOCTYPE html PUBLIC "-//W3C//DTD XHT...    1         0
10368  \r\n<!DOC

In [41]:
# juan = empleados.loc[empleados['Nombre'] == 'Juan']
# print(juan)
df3 = df.loc[df['phishing'] == 1]
print(df3)

                                                contexts  ham  phishing
997    <html xmlns="http://www.w3.org/1999/xhtml"><he...    0         1
998    <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//...    0         1
999    <?xml version="1.0" encoding="UTF-8"?>\r\n<!DO...    0         1
1000   <!DOCTYPE html PUBLIC "-//IETF//DTD HTML 2.0//...    0         1
1001   <!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//...    0         1
1002   <!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 T...    0         1
1003   <!DOCTYPE html PUBLIC "-//IETF//DTD HTML 2.0//...    0         1
1004   <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 S...    0         1
1005   <!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//...    0         1
1006   <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 T...    0         1
1007   <!DOCTYPE html PUBLIC "-//IETF//DTD HTML 2.0//...    0         1
1008   <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 T...    0         1
1009   <html lang="en-GB" xmlns="http://www.w3.org/19...    0   

In [81]:
webpage_html = df['contexts'][15]

In [67]:
# webpage_html = '<!DOCTYPE html>\r\n<html xmlns="http://www.w3.org/1999/xhtml"><head><meta content="text/html;charset=gb2312" http-equiv="Content-Type" /><title>?????????      </title><style>html{overflow-y:auto}body{font:12px arial;text-align:center;background:#fff}body,p,form,ul,li{margin:0;padding:0;list-style:none}body,form,#fm{position:relative}td{text-align:left}img{border:0}a{color:#00c}a:active{color:#f60}#u{color:#999;padding:4px 10px 5px 0;text-align:right}#u a{margin:0 5px}#u .reg{margin:0}#m{width:680px;margin:0 auto;}#nv a,#nv b,.btn,#lk{font-size:14px}#fm{padding-left:90px;text-align:left}input{border:0;padding:0}#nv{height:19px;font-size:16px;margin:0 0 4px;text-align:left;text-indent:117px}.s_ipt_wr{width:418px;height:30px;display:inline-block;margin-right:5px;background:url(http://www.baidu.com/img/i-1.0.0.png) no-repeat -304px 0;border:1px solid #b6b6b6;border-color:#9a9a9a #cdcdcd #cdcdcd #9a9a9a;vertical-align:top}.s_ipt{width:405px;height:22px;font:16px/22px arial;margin:5px 0 0 7px;background:#fff;outline:none;-webkit-appearance:none}.s_btn{width:95px;height:32px;padding-top:2px\\9;font-size:14px;background:#ddd url(http://www.baidu.com/img/i-1.0.0.png);cursor:pointer}.s_btn_h{background-position:-100px 0}.s_btn_wr{width:97px;height:34px;display:inline-block;background:url(http://www.baidu.com/img/i-1.0.0.png) no-repeat -202px 0;*position:relative;z-index:0;vertical-align:top}#lg img{vertical-align:top;margin-bottom:3px}#lk{margin:33px 0}#lk span{font:14px "??"}#lm{height:60px}#lh{margin:16px 0 5px;word-spacing:3px}.tools{position:absolute;top:-4px;*top:10px;right:-13px;}#mHolder{width:62px;position:relative;z-index:296;display:none}#mCon{height:18px;line-height:18px;position:absolute;cursor:pointer;padding:0 18px 0 0;background:url(http://www.baidu.com/img/bg-1.0.0.gif) no-repeat right -134px;background-position:right -136px\\9}#mCon span{color:#00c;cursor:default;display:block}#mCon .hw{text-decoration:underline;cursor:pointer}#mMenu a{width:100%;height:100%;display:block;line-height:22px;text-indent:6px;text-decoration:none;filter:none\\9}#mMenu,#user ul{box-shadow:1px 1px 2px #ccc;-moz-box-shadow:1px 1px 2px #ccc;-webkit-box-shadow:1px 1px 2px #ccc;filter: progid:DXImageTransform.Microsoft.Shadow(Strength=2, Direction=135, Color="#cccccc")\\9;}#mMenu{width:56px;border:1px solid #9b9b9b;list-style:none;position:absolute;right:7px;top:28px;display:none;background:#fff}#mMenu a:hover{background:#ebebeb}#mMenu .ln{height:1px;background:#ebebeb;overflow:hidden;font-size:1px;line-height:1px;margin-top:-1px}#cp,#cp a{color:#77c}#seth{display:none;behavior:url(#default#homepage)}#setf{display:none}</style>\n<script type="text/javascript">function h(obj){obj.style.behavior=\'url(#default#homepage)\';var a = obj.setHomePage(\'http://www.baidu.com/\');}</script></head>\n\n<body><div id="u"><a name="tj_setting" href="http://www.baidu.com/gaoji/preferences.html">????</a>|<a name="tj_login" href="http://passport.baidu.com/?login&amp;tpl=mn">??</a><a class="reg" name="tj_reg" href="https://passport.baidu.com/?reg&amp;tpl=mn">??</a></div>\n<div id="m"><p id="lg"><img height="129" width="270" usemap="#mp" src="http://www.baidu.com/img/baidu_sylogo1.gif" /><map name="mp"><area title="???? ?????" target="_blank" href="http://hi.baidu.com/baidu/" coords="40,25,230,95" shape="rect" /></map></p><p id="nv"><a href="http://news.baidu.com" name="tj_news">?Â\xa0?</a>?<b>?Â\xa0?</b>?<a href="http://tieba.baidu.com" name="tj_tieba">?Â\xa0?</a>?<a href="http://zhidao.baidu.com" name="tj_zhidao">?Â\xa0?</a>?<a href="http://mp3.baidu.com" name="tj_mp3">MP3</a>?<a href="http://image.baidu.com" name="tj_img">?Â\xa0?</a>?<a href="http://video.baidu.com" name="tj_video">?Â\xa0?</a>?<a href="http://map.baidu.com" name="tj_map">?Â\xa0?</a></p><div id="fm"><form action="/s" name="f"><span class="s_ipt_wr"><input type="text" class="s_ipt" maxlength="100" id="kw" name="wd" autocomplete="off" /></span><input type="hidden" value="0" name="rsv_bp" /><input type="hidden" value="3" name="rsv_spt" /><span class="s_btn_wr"><input type="submit" onmouseout="this.className=\'s_btn\'" onmousedown="this.className=\'s_btn s_btn_h\'" class="s_btn" id="su" value="????" /></span><div id="sd_1330360745032" style="display: none;"></div></form><span class="tools"><span id="mHolder"><div id="mCon"><span>???</span></div></span></span><ul id="mMenu"><li><a name="ime_hw" href="#">??</a></li><li><a name="ime_py" href="#">??</a></li><li class="ln"></li><li><a name="ime_cl" href="#">??</a></li></ul></div>\n<p id="lk"><a href="http://hi.baidu.com" name="tj_hi">??</a>?<a href="http://baike.baidu.com" name="tj_baike">??</a>?<a href="http://www.hao123.com" name="tj_hao123">hao123</a><span> | <a href="/more/" name="tj_more">??&gt;&gt;</a></span></p><p id="lm"></p><p><a onmousedown="return ns_c({\'fm\':\'behs\',\'tab\':\'homepage\',\'pos\':0})" href="http://utility.baidu.com/traf/click.php?id=215&amp;url=http://www.baidu.com" onclick="h(this)" id="seth">???????</a><a onmousedown="return ns_c({\'fm\':\'behs\',\'tab\':\'favorites\',\'pos\':0})" href="javascript:void(0)" onclick="fa(this)" id="setf" style="display: inline;">???????</a></p>\n<p id="lh"><a href="http://e.baidu.com/?refer=888">??????</a> | <a href="http://top.baidu.com">?????</a> | <a href="http://home.baidu.com">????</a> | <a href="http://ir.baidu.com">About Baidu</a></p><p id="cp">©2012 Baidu <a href="/duty/">???????</a> <a target="_blank" href="http://www.miibeian.gov.cn">?ICP?030173?</a> <img src="http://gimg.baidu.com/img/gs.gif" /></p></div>\n\n<script>var bdUser = null;var w=window,d=document,n=navigator,k=d.f.wd,a=d.getElementById("nv").getElementsByTagName("a"),isIE=n.userAgent.indexOf("MSIE")!=-1&amp;&amp;!window.opera;for(var i=0;i&lt;a.length;i++){a[i].onclick=function(){if(k.value.length&gt;0){var o=this,h=o.href,q=encodeURIComponent(k.value);if(h.indexOf("q=")!=-1){o.href=h.replace(/q=[^&amp;\\x24]*/,"q="+q)}else{this.href+="?q="+q}}}};(function(){if(/q=([^&amp;]+)/.test(location.search)){k.value=decodeURIComponent(RegExp["\\x241"])}})();if(n.cookieEnabled&amp;&amp;!/sug?=0/.test(d.cookie)){d.write(\'&lt;script src=http://www.baidu.com/cache/sug/js/bdsug-1.1.js&gt;&lt;\\/script&gt;\')};function addEV(o, e, f){if(w.attachEvent){o.attachEvent("on" + e, f);}else if(w.addEventListener){ o.addEventListener(e, f, false);}}function G(id){return d.getElementById(id);}function ns_c(q){var p = encodeURIComponent(window.document.location.href), sQ = \'\', sV = \'\', mu=\'\', img = window["BD_PS_C" + (new Date()).getTime()] = new Image();for (v in q) {sV = q[v];sQ += v + "=" + sV + "&amp;";} mu= "&amp;mu=" + p ;img.src = "http://nsclick.baidu.com/v.gif?pid=201&amp;pj=www&amp;" + sQ + "path="+p+"&amp;t="+new Date().getTime();return true;}if(/\\bbdime=[12]/.test(d.cookie)){document.write(\'&lt;script src=http://www.baidu.com/cache/ime/js/openime-1.0.0.js&gt;&lt;\\/script&gt;\');}(function(){var user = G("user"), userMenu = G("userMenu");if(user &amp;&amp; userMenu){user.onmouseover = function(){userMenu.style.display = "block"};user.onmouseout = function(){userMenu.style.display = "none"};}})();(function(){var u = G("u").getElementsByTagName("a"), nv = G("nv").getElementsByTagName("a"), lk = G("lk").getElementsByTagName("a"), un = "";var tj_nv = ["news","tieba","zhidao","mp3","img","video","map"];var tj_lk = ["hi","baike","hao123","more"];un = bdUser == null ? "" : bdUser;function _addTJ(obj){addEV(obj, "mousedown", function(e){var e = e || window.event;var target = e.target || e.srcElement;ns_c({\'fm\':\'behs\',\'tab\':target.name||\'tj_user\',\'un\':encodeURIComponent(un)});});}for(var i = 0; i &lt; u.length; i++){_addTJ(u[i]);}for(var i = 0; i &lt; nv.length; i++){nv[i].name = \'tj_\' + tj_nv[i];_addTJ(nv[i]);}for(var i = 0; i &lt; lk.length; i++){lk[i].name = \'tj_\' + tj_lk[i];_addTJ(lk[i]);}})();addEV(w,"load",function(){k.focus()});w.onunload=function(){};</script><script src="http://www.baidu.com/cache/sug/js/bdsug-1.1.js"></script>\n\n\n\n\n\n<script src="http://www.baidu.com/cache/hps/js/hps-1.4.js" type="text/javascript"></script>\n\n<!--d01a5ab4c0f73034--></body></html>'

In [82]:
webpage_html

'<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">\r\n<html xmlns="http://www.w3.org/1999/xhtml" lang="ja"><head>\n<meta content="text/html; charset=utf-8" http-equiv="content-type" />\n<meta content="text/css" http-equiv="content-style-type" />\n<meta content="text/javascript" http-equiv="content-script-type" />\n<meta content="?????????????????????????????????????????????????80?????????????????????????????????????????????" name="description" />\n<title>Yahoo! JAPAN</title>\n<base href="http://www.yahoo.co.jp/_ylh=X3oDMTB0NWxnaGxsBF9TAzIwNzcyOTYyNjUEdGlkAzEyBHRtcGwDZ2Ex/" />\n<style type="text/css">&lt;!--\nbody,div,dl,dt,dd,ul,ol,li,h1,h2,h3,h4,h5,h6,pre,form,fieldset,input,button,p,blockquote{margin:0;padding:0;}fieldset,img{border:0;}table{border-collapse:collapse;border-spacing:0;}address,caption,cite,code,dfn,em,th,var{font-style:normal;font-weight:normal;}ol,ul{list-style:none;}.separate,.floatingw,legend{display:none;}button{

In [83]:
len(webpage_html)

93650

In [12]:
from nltk.stem.wordnet import WordNetLemmatizer
from nltk import pos_tag
from nltk.corpus import wordnet
from nltk.corpus import stopwords
from nltk.stem.wordnet import WordNetLemmatizer
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
import nltk
# nltk.download('stopwords')
# nltk.download('wordnet')
# nltk.download('punkt')
# nltk.download('averaged_perceptron_tagger')

#Lemmatize Words

def fetch_pos_tag(tag):
    if tag.startswith('J'):
        return wordnet.ADJ
    elif tag.startswith('V'):
        return wordnet.VERB
    elif tag.startswith('N'):
        return wordnet.NOUN
    elif tag.startswith('R'):
        return wordnet.ADV
    else:
        # As default pos in lemmatization is Noun
        return wordnet.NOUN

lemmatizer = WordNetLemmatizer()

#cleaning the data now 

regex = [
    r'<[^>]+>', #HTML tags
    r'@(\w+)', # @-mentions
    r"#(\w+)", # hashtags
    r'http[s]?://(?:[a-z]|[0-9]|[$-_@.&+]|[!*\(\),]|(?:%[0-9a-f][0-9a-f]))+', # URLs
    r'[^0-9a-z #+_\\r\\n\\t]', #BAD SYMBOLS
]

REPLACE_URLS = re.compile(r'http[s]?://(?:[a-z]|[0-9]|[$-_@.&+]|[!*\(\),]|(?:%[0-9a-f][0-9a-f]))+')
REPLACE_HASH = re.compile(r'#(\w+)')
REPLACE_AT = re.compile(r'@(\w+)')
REPLACE_HTML_TAGS = re.compile(r'<[^>]+>')
REPLACE_DIGITS = re.compile(r'\d+')
#REPLACE_BY = re.compile(r"[/(){}\[\]\|,;.:?\-\'\"$]")
REPLACE_BY = re.compile(r"[^a-z0-9\-]")

STOPWORDS = set(stopwords.words('english'))

#tokens_re = re.compile(r'('+'|'.join(regex)+')', re.VERBOSE | re.IGNORECASE)

# sentences = [] #for Word2Vec model

def clean_text(text):
    text = text.lower()
    text = REPLACE_HTML_TAGS.sub(' ', text)
    text = REPLACE_URLS.sub('', text)
    text = REPLACE_HASH.sub('', text)
    text = REPLACE_AT.sub('', text)
    text = REPLACE_DIGITS.sub(' ', text)
    text = REPLACE_BY.sub(' ', text)
    
    
    text = " ".join(lemmatizer.lemmatize(word.strip(), fetch_pos_tag(pos_tag([word.strip()])[0][1])) for word in text.split() if word not in STOPWORDS and len(word)>3)
    
    #sentences.append(text.split())
    return text



In [84]:
webpage_text = clean_text(webpage_html)

In [85]:
webpage_text

'yahoo japan body form fieldset input button blockquote margin pad fieldset border table border-collapse collapse border-spacing address caption cite code font-style normal font-weight normal list-style none separate floatingw legend display none button cursor pointer body font-family pgothic osaka arial sans-serif line-height font-size text-align center word-wrap break-word table font-size inherit font code samp font-family monospace line-height font-size contentbox font-size table font-size span assist cite cite font-size span font-weight normal visit color text-decoration none visit color hover text-decoration underline button cursor pointer position relative min-width width width margin auto position relative z-index padding-bottom zoom content display block clear text-align left float left position relative z-index width min-width float right position relative z-index min-width width float left min-width width float right min-width width item emphasis connect rank pldwn plup prev 

In [75]:
len(webpage_text)

23685

In [86]:
tokenizer = Tokenizer(num_words=3000)
tokenizer.fit_on_texts(webpage_text)
webpage_text = tokenizer.texts_to_sequences(webpage_text)
vocab_size = len(tokenizer.word_index) + 1
maxlen = 200
webpage_text = pad_sequences(webpage_text, padding='post', maxlen=maxlen)

In [87]:
webpage_text.shape

(30152, 200)

# **Prediction**

In [88]:
# Load model
from tensorflow.keras.models import load_model
model1 = load_model('Bi_GRU_model.h5')
model1.summary()

Model: "functional_1"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_3 (InputLayer)            [(None, 200)]        0                                            
__________________________________________________________________________________________________
embedding_2 (Embedding)         (None, 200, 100)     14423600    input_3[0][0]                    
__________________________________________________________________________________________________
spatial_dropout1d_2 (SpatialDro (None, 200, 100)     0           embedding_2[0][0]                
__________________________________________________________________________________________________
bidirectional_2 (Bidirectional) (None, 200, 256)     176640      spatial_dropout1d_2[0][0]        
_______________________________________________________________________________________

In [19]:
new_arr = webpage_text.reshape((1, 200))

ValueError: cannot reshape array of size 512200 into shape (1,200)

In [89]:
results = model1.predict(webpage_text)

In [79]:
results.shape

(23685, 2)

In [90]:
results

array([[0.01587591, 0.9880921 ],
       [0.01344311, 0.98929363],
       [0.0149872 , 0.9880235 ],
       ...,
       [0.01324543, 0.9888278 ],
       [0.0149872 , 0.9880235 ],
       [0.0149872 , 0.9880235 ]], dtype=float32)

In [23]:
results[:, 0]

array([0.0149872 , 0.0149872 , 0.0149872 , ..., 0.01711884, 0.02047846,
       0.02873099], dtype=float32)

In [24]:
lista = results[:, 0]

In [25]:
lista

array([0.0149872 , 0.0149872 , 0.0149872 , ..., 0.01711884, 0.02047846,
       0.02873099], dtype=float32)

In [26]:
n1 = 0
n2 = 0

for numero in lista:
       if numero < 0.5:
           n1 = n1 + 1
       else:
           n2 = n2 + 1
print(n1)
print(n2)


2561
0


In [60]:
n1=0
n2=0
for i in lista.index:
    if results.loc[i, 0] == 0:
        n1 = n1 + 1
    #     n1 = len((train_df.loc[i, 'contexts']).split())
#     train_df.loc[i, 'nwords'] = n1
#     n2 = n2 + n1
print (i)
print (n1)

AttributeError: 'numpy.ndarray' object has no attribute 'index'

# **BI-GRU**

In [20]:
# from sklearn.metrics import roc_curve, auc, roc_auc_score
import tensorflow as tf
# from tensorflow.keras.layers import Conv1D, Bidirectional, GlobalMaxPool1D, MaxPooling1D, BatchNormalization, Add, Flatten


# Copiado de GRU ************

from tensorflow.keras import initializers, regularizers, constraints, optimizers, layers, callbacks
from tensorflow.keras.callbacks import EarlyStopping,ModelCheckpoint
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.preprocessing import text, sequence
from tensorflow.keras import initializers, regularizers, constraints, optimizers, layers
from tensorflow.keras import Model, Input, Sequential
from tensorflow.keras.layers import Dense, Input, LSTM, SimpleRNN, Embedding, Dropout, SpatialDropout1D, Activation, Conv1D,GRU
from tensorflow.keras.layers import Conv1D, Bidirectional, GlobalMaxPool1D, MaxPooling1D, BatchNormalization, Add, Flatten
from tensorflow.keras.layers import GlobalMaxPooling1D, GlobalAveragePooling1D, concatenate, SpatialDropout1D

# **********

deep_inputs = Input(shape=(maxlen,))
embedding_layer = Embedding(vocab_size, 100, weights=[embedding+_matrix], trainable=False)(deep_inputs)
model = SpatialDropout1D(0.2)(embedding_layer)
model = Bidirectional(GRU(128,return_sequences=True,dropout=0.1,recurrent_dropout=0.1 ))(model)
model = Conv1D(64, kernel_size = 3, padding = "valid", kernel_initializer = "glorot_uniform")(model)
avg_pool = GlobalAveragePooling1D()(model)
max_pool = GlobalMaxPooling1D()(model)
model = concatenate([avg_pool, max_pool])
dense_layer1 = Dense(2, activation="sigmoid")(model)
Bi_GRU_glove = Model(deep_inputs, dense_layer1)
Bi_GRU_glove.compile(loss='binary_crossentropy',optimizer='adam',metrics=[tf.keras.metrics.AUC()])

In [21]:
Bi_GRU_glove.summary()

Model: "functional_1"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_3 (InputLayer)            [(None, 200)]        0                                            
__________________________________________________________________________________________________
embedding_2 (Embedding)         (None, 200, 100)     14423600    input_3[0][0]                    
__________________________________________________________________________________________________
spatial_dropout1d_2 (SpatialDro (None, 200, 100)     0           embedding_2[0][0]                
__________________________________________________________________________________________________
bidirectional_2 (Bidirectional) (None, 200, 256)     176640      spatial_dropout1d_2[0][0]        
_______________________________________________________________________________________

In [23]:
from tensorflow.keras.models import load_model

# Guardar el modelo en un archivo
Bi_GRU_glove.save('Bi_GRU_model.h5')

In [29]:
from tensorflow.keras.models import load_model

# Cargar el modelo desde el archivo
model1 = load_model('Bi_GRU_model.h5')

In [5]:
X_train[506]
# len(X_train[500])

NameError: name 'X_train' is not defined

In [53]:
# import numpy as np
# Arreglo incialmente con forma (200,)
# arr = np.array([1, 2, 3, ..., 200])
# Cambiar la forma a (1, 200)
new_arr = X_train[506].reshape((1, 200))

In [ ]:
results = Bi_GRU_glove.predict(new_arr)

In [104]:
pred_prob =  Bi_GRU_glove.predict_on_batch(X_test)

In [106]:
y_truep = y_test[:, 0]
y_truep = (y_truep>0.5)
y_predp = y_pred[:, 0]
y_predp = (y_predp>0.5)

y_trueh = y_test[:, 1]
y_trueh = (y_trueh>0.5)
y_predh = y_pred[:, 1]
y_predh = (y_predh>0.5)

cm = confusion_matrix(y_truep, y_predp)
print (cm)
tnp, fpp, fnp, tpp = confusion_matrix(y_truep, y_predp).ravel()
print("True positives (TP):", tpp)
print("False positives (FP):", fpp)
print("True negatives (TN):", tnp)
print("False negatives (FN):", fnp)

cm = confusion_matrix(y_trueh, y_predh)
print (cm)
tnh, fph, fnh, tph = confusion_matrix(y_trueh, y_predh).ravel()
print("True positives (TP):", tph)
print("False positives (FP):", fph)
print("True negatives (TN):", tnh)
print("False negatives (FN):", fnh)

[[1787   45]
 [  71  172]]
True positives (TP): 172
False positives (FP): 45
True negatives (TN): 1787
False negatives (FN): 71
[[ 173   70]
 [  43 1789]]
True positives (TP): 1789
False positives (FP): 70
True negatives (TN): 173
False negatives (FN): 43


In [107]:
from sklearn.metrics import f1_score
from sklearn.metrics import precision_score

print("Medidas con Phishing")

recall = tpp / (tpp + fnp)
print("Recall:", recall)

f1 = f1_score(y_truep, y_predp)
print("F1 Score:", f1)

precision = precision_score(y_truep, y_predp)
print("Precision:", precision)

print("Medidas con Ham")

recall = tph / (tph + fnh)
print("Recall:", recall)

f1 = f1_score(y_trueh, y_predh)
print("F1 Score:", f1)

precision = precision_score(y_trueh, y_predh)
print("Precision:", precision)

Medidas con Phishing
Recall: 0.7078189300411523
F1 Score: 0.7478260869565218
Precision: 0.7926267281105991
Medidas con Ham
Recall: 0.976528384279476
F1 Score: 0.969384990517475
Precision: 0.9623453469607316


In [109]:
y_test_flattened = y_test.reshape(-1)
print(y_test_flattened)

[0 1 0 ... 1 0 1]


In [110]:
y_pred_flattened = y_pred.reshape(-1)
print(y_pred_flattened)

[3.7759706e-05 9.9996698e-01 1.6696781e-02 ... 9.9995679e-01 1.1086467e-01
 9.2360020e-01]


In [111]:
y_pred_flattened = (y_pred_flattened>0.5)
y_pred_flattened

array([False,  True, False, ...,  True, False,  True])

In [114]:
y_test_flattened = (y_test_flattened > 0.5)
y_test_flattened
y_test_flattened.dtype

dtype('bool')

In [115]:
cm = confusion_matrix(y_test_flattened, y_pred_flattened)
print (cm)
tnf, fpf, fnf, tpf = confusion_matrix(y_test_flattened, y_pred_flattened).ravel()
print("True positives (TP):", tpf)
print("False positives (FP):", fpf)
print("True negatives (TN):", tnf)
print("False negatives (FN):", fnf)


[[1960  115]
 [ 114 1961]]
True positives (TP): 1961
False positives (FP): 115
True negatives (TN): 1960
False negatives (FN): 114
